Tyler VanHaren's Homework 1

In [0]:
import numpy as np
from numpy import linalg as la
import math
import cmath

Problem 1

We start out by simply creating all the pauli operators

In [0]:
theta_x = np.array([[0,1],[1,0]])
theta_y = np.array([[0,-1j],[1j,0]])
theta_z = np.array([[1,0],[0,-1]])

In [142]:
print(theta_x)
print(theta_y)
print(theta_z)

[[0 1]
 [1 0]]
[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
[[ 1  0]
 [ 0 -1]]


Numpy's linalg library has the ability to calculate the eigenbasis for us: they will be stored in the second return slot

In [0]:

basis_x = la.eig(theta_x)[1]
basis_y = la.eig(theta_y)[1]
basis_z = la.eig(theta_z)[1]
basis = [basis_x,basis_y,basis_z]

In [144]:
print('Eigenbasis for x',basis_x)
print('Eigenbasis for y',basis_y)
print('Eigenbasis for z',basis_z)

Eigenbasis for x [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Eigenbasis for y [[-0.        -0.70710678j  0.70710678+0.j        ]
 [ 0.70710678+0.j          0.        -0.70710678j]]
Eigenbasis for z [[1. 0.]
 [0. 1.]]


Now we just take the inner product of all the vectors, the absolute value of that, and the square of that (with some rounding to avoid messy .4999999999 and .50000000001 due to imprecision)

In [145]:
for i in range(0,len(basis)):
  for j in range(0,len(basis)):
    if i==j:
      continue
    for vector_a in basis[i]:
      for vector_b in basis[j]:
        q = np.absolute(np.inner(vector_a,vector_b))**2
        print(np.round(q,decimals=5))

0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5
0.5


We can see that all values are within an epsilon of 1/2, which is expected for d=2

Problem 2:


$$ <A,B>_{TR} = TR(A^\dagger B) $$
To show that this is an inner product, three things must be proven:
Linearity in the second argument, conjugate commutivity, and non-negativity.

1. Linearity in the Second Argument

The Claim
$$ <A, \sum_{i}\lambda_{i}B_{i}>_{TR} =  \sum_{i}\lambda_{i} <A,B>_{TR}$$

Proof
$$ TR(A^\dagger \sum_{i}\lambda_{i} B_i)$$
$$ = \sum_{i=1}^d<b_i|A^\dagger \sum_{i}\lambda_{i}Bi|b_i>$$
where $\{|b_i>\}$ form an orthonormal basis
$$=  \sum_{i=1}^d<b_i|\sum_{i}\lambda_{i} A^\dagger B|b_i>$$ 
$$ =  \sum_{i}\lambda_{i} \sum_{i=1}^d<b_i|A^\dagger B|b_i>$$
$$ = \sum_{i}\lambda_{i} TR(A\dagger,B)$$

2. Conjugate-commutativity

The Claim
$$ <A,B>_{TR} = <B,A>_{TR}^* $$

Proof
$$ TR(A^\dagger  B)$$
$$ = TR((B^\dagger A)^*)$$
$$ = TR(B^\dagger A)^*$$

3. Non-negativity

The Claim
$$<A,A>_{TR} \geq 0 $$
With equal to zero only if A is all zero

Proof
$$<A,A>_{TR}$$
$$ TR(A^\dagger A)$$
$$ = \sum_{i=1}^d<b_i|A^\dagger A|b_i>$$
$$ = \sum_{i=1}^dV_i^\dagger V_i$$
where V is the vector formed by taking ket b times A
$$=\sum_{i=1}^d \sum_{j=1}^d \overline{v_{i,j}}v_{i,j}$$
$$=\sum_{i=1}^d \sum_{j=1}^d |v_{i,j}|^2$$
which will always be positive, and only zero when all $v_{i,j}$ are 0

Problem 3:

Since we're showing that this works via code, we can set the dimension arbitrarily, I chose 5 since it shows there's a bit of a generalization from the d=2 case and our pauli operator friends, but since there is d^2 output I kept it smaller

In [0]:
D = 5


Some helper functions:

bra and ket just return the corresponding bra/ket

matexpo raises a matrix to a power so I don't have to multiply them over and over manually

traceProduct computes the trace inner product as seen in the last problem

In [0]:
def bra(x):
  arr = np.zeros((D,1))
  arr[x]=1
  return arr
def ket(x):
  arr = np.zeros((1,D))
  arr[0][x] = 1
  return arr

In [0]:
def matexpo(M, power):
  if power == 0:
    return np.identity(D)
  if power%2 == 1:
    return np.matmul(M,matexpo(M,power-1))
  half = matexpo(M,power/2)
  return np.matmul(half,half)

In [0]:
def traceProduct(A,B):
  return np.trace(np.matmul(np.matrix(A).getH(),np.matrix(B)))

Setting up the X and Z matrices

In [150]:
X = np.zeros((D,D))
for i in range(0,D):
  X += np.outer(ket((i+1)%D),bra(i%D))

w = cmath.exp(2j*math.pi/D)
Z = np.zeros((D,D),dtype=np.complex_)
for i in range(0,D):
  Z += (w**i)*np.outer(ket(i),bra(i))
print('X')
print(X)
print('Z')
print(Z)


X
[[0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
Z
[[ 1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.30901699+0.95105652j  0.        +0.j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j         -0.80901699+0.58778525j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
  -0.80901699-0.58778525j  0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.30901699-0.95105652j]]


Compute all the matrices now

There are d^2 as expected, and I output a few just to see what they looked like

In [157]:

Ms = []
for a in range(0,D):
  for b in range(0,D):
    x = np.matmul(matexpo(X,a),matexpo(Z,b))
    Ms.append(x)
print(len(Ms))

print(Ms[0])
print(Ms[1])
print(Ms[7])

25
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.30901699+0.95105652j  0.        +0.j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j         -0.80901699+0.58778525j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
  -0.80901699-0.58778525j  0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.30901699-0.95105652j]]
[[ 0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j         -0.80901699-0.58778525j]
 [ 1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j         -0.80901699+0.58778525j  0.        +0.j
   0.       

Time to put the trace inner products to the test

In [152]:
for i in range(0,len(Ms)):
  for j in range(0,len(Ms)):
    if i==j:
      continue
    traceP = traceProduct(Ms[i],Ms[j])
    print(i,j,np.round(traceP,decimals=2))

0 1 (-0+0j)
0 2 0j
0 3 0j
0 4 -0j
0 5 0.0
0 6 0j
0 7 0j
0 8 0j
0 9 0j
0 10 0.0
0 11 0j
0 12 0j
0 13 0j
0 14 0j
0 15 0.0
0 16 0j
0 17 0j
0 18 0j
0 19 0j
0 20 0.0
0 21 0j
0 22 0j
0 23 0j
0 24 0j
1 0 (-0-0j)
1 2 0j
1 3 0j
1 4 0j
1 5 0j
1 6 0j
1 7 0j
1 8 0j
1 9 0j
1 10 0j
1 11 0j
1 12 0j
1 13 0j
1 14 0j
1 15 0j
1 16 0j
1 17 0j
1 18 0j
1 19 0j
1 20 0j
1 21 0j
1 22 0j
1 23 0j
1 24 0j
2 0 -0j
2 1 -0j
2 3 0j
2 4 0j
2 5 0j
2 6 0j
2 7 0j
2 8 0j
2 9 0j
2 10 0j
2 11 0j
2 12 0j
2 13 0j
2 14 0j
2 15 0j
2 16 0j
2 17 0j
2 18 0j
2 19 0j
2 20 0j
2 21 0j
2 22 0j
2 23 0j
2 24 0j
3 0 0j
3 1 -0j
3 2 -0j
3 4 0j
3 5 0j
3 6 0j
3 7 0j
3 8 0j
3 9 0j
3 10 0j
3 11 0j
3 12 0j
3 13 0j
3 14 0j
3 15 0j
3 16 0j
3 17 0j
3 18 0j
3 19 0j
3 20 0j
3 21 0j
3 22 0j
3 23 0j
3 24 0j
4 0 0j
4 1 0j
4 2 -0j
4 3 -0j
4 5 0j
4 6 0j
4 7 0j
4 8 0j
4 9 0j
4 10 0j
4 11 0j
4 12 0j
4 13 0j
4 14 0j
4 15 0j
4 16 0j
4 17 0j
4 18 0j
4 19 0j
4 20 0j
4 21 0j
4 22 0j
4 23 0j
4 24 0j
5 0 0.0
5 1 0j
5 2 0j
5 3 0j
5 4 0j
5 6 (-0+0j)
5 7 0j
5 8 0j
5 

All trace inner products are 0, so these are all orthogonal to each other with respect to the trace inner product!